import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { Toaster } from "sonner";
import { checkUser } from "@/lib/checkUser";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AiVana",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await checkUser();
  const isAdmin = user?.role === "ADMIN";
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header isAdmin={isAdmin}/>

        <main className="min-h-screen lg:mt-0 sm:mt-10 mt-12">{children}</main>
        <Toaster richColors />

        <footer className="w-full relative z-80"><Footer/></footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
